name: Export de métricas

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Criar diretório
        run: mkdir analytics-raw-data

      - name: Coletar métricas
        run: python parser.py ${{ github.event.repository.name }} ${{ github.ref_name }}

      - name: Adiciona resultado das métricas
        uses: actions/upload-artifact@v3
        with:
          name: metrics_results
          path: ./analytics-raw-data/*

      - name: Envia métricas para repo de Doc
        run: |
          git config --global user.email "${{secrets.USER_EMAIL}}"
          git config --global user.name "${{secrets.USER_NAME}}"
          git clone --single-branch --branch main "https://x-access-token:${{secrets.API_TOKEN_DOC_REPOSITORY}}@github.com/fga-eps-mds/2021-2-SysArq-Doc.git" doc_repo
          mkdir -p doc_repo/analytics-raw-data
          cp -R analytics-raw-data/*.json doc_repo/analytics-raw-data
          cd doc_repo
          git add .
          git commit -m "Adds metric file from ${{ github.event.repository.name }} ${{ github.ref_name }}"
          git push
